### ISSUE TITLE
Illegal state exception is thrown when refreshing the browser

### ISSUE THREAD

**Issue by dhuebner** [eclipse/sprotty-server#8] opened 2018-11-23 13:30 UTC
Happens during debugging using backend socket 

```
Caused by: java.lang.IllegalStateException: This language server has already been initialized.
	at org.eclipse.xtext.ide.server.LanguageServerImpl.initialize(LanguageServerImpl.java:225)
	at org.eclipse.sprotty.xtext.ls.DiagramLanguageServer.initialize(DiagramLanguageServer.java:97)
	... 16 more
```

**Comment by JanKoehnlein** [comment] 2019-02-20 13:32
Fixed in the meantime. This was caused by the socket being used before being connected.

**Closed by JanKoehnlein** 2019-02-20 13:32 UTC
